/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as RegrasIndexRouteImport } from './routes/regras.index'
import { Route as RegrasSlugRouteImport } from './routes/regras.$slug'
import { Route as ApiPublicMidiaSplatRouteImport } from './routes/api/public/midia.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RegrasIndexRoute = RegrasIndexRouteImport.update({
  id: '/regras/',
  path: '/regras/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasSlugRoute = RegrasSlugRouteImport.update({
  id: '/regras/$slug',
  path: '/regras/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMidiaSplatRoute = ApiPublicMidiaSplatRouteImport.update({
  id: '/api/public/midia/$',
  path: '/api/public/midia/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/regras/$slug': typeof RegrasSlugRoute
  '/regras/': typeof RegrasIndexRoute
  '/api/public/midia/$': typeof ApiPublicMidiaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/regras/$slug': typeof RegrasSlugRoute
  '/regras': typeof RegrasIndexRoute
  '/api/public/midia/$': typeof ApiPublicMidiaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/regras/$slug': typeof RegrasSlugRoute
  '/regras/': typeof RegrasIndexRoute
  '/api/public/midia/$': typeof ApiPublicMidiaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/regras/$slug'
    | '/regras/'
    | '/api/public/midia/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/regras/$slug'
    | '/regras'
    | '/api/public/midia/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/regras/$slug'
    | '/regras/'
    | '/api/public/midia/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegrasSlugRoute: typeof RegrasSlugRoute
  RegrasIndexRoute: typeof RegrasIndexRoute
  ApiPublicMidiaSplatRoute: typeof ApiPublicMidiaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/regras/': {
      id: '/regras/'
      path: '/regras'
      fullPath: '/regras/'
      preLoaderRoute: typeof RegrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras/$slug': {
      id: '/regras/$slug'
      path: '/regras/$slug'
      fullPath: '/regras/$slug'
      preLoaderRoute: typeof RegrasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/midia/$': {
      id: '/api/public/midia/$'
      path: '/api/public/midia/$'
      fullPath: '/api/public/midia/$'
      preLoaderRoute: typeof ApiPublicMidiaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegrasSlugRoute: RegrasSlugRoute,
  RegrasIndexRoute: RegrasIndexRoute,
  ApiPublicMidiaSplatRoute: ApiPublicMidiaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
